<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
  <Actions category="tool-shortcuts">
      <text>Tool Shortcuts</text>
     <Action name="KisToolPath">
      <icon>krita_draw_path</icon>
      <text>Line/Curve Tool</text>
      <whatsThis>Draw a straight segment and shape it into a curve without exposed Bezier handles.</whatsThis>
      <toolTip>Line/Curve Tool</toolTip>
      <iconText>Line/Curve Tool</iconText>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip>Draw and shape a simple Line/Curve</statusTip>
    </Action>
  </Actions>
</ActionCollection>
